Started by user [8mha:////4Efp0/2sqJSHgOp2keW96WryiSDlF4ojeq0gs4pJGmDwAAAAlx+LCAAAAAAAAP9b85aBtbiIQTGjNKU4P08vOT+vOD8nVc83PyU1x6OyILUoJzMv2y+/JJUBAhiZGBgqihhk0NSjKDWzXb3RdlLBUSYGJk8GtpzUvPSSDB8G5tKinBIGIZ+sxLJE/ZzEvHT94JKizLx0a6BxUmjGOUNodHsLgAzWEgZu/dLi1CL9xJTczDwAj6GcLcAAAAA=[0mManoj
Building remotely on [8mha:////4CfGTJCS+Bn6z+jBdG+ux4JOXLqDIMx5qBhBobH9EMYhAAAApB+LCAAAAAAAAP9b85aBtbiIQTGjNKU4P08vOT+vOD8nVc83PyU1x6OyILUoJzMv2y+/JJUBAhiZGBgqihhk0NSjKDWzXb3RdlLBUSYGJk8GtpzUvPSSDB8G5tKinBIGIZ+sxLJE/ZzEvHT94JKizLx0a6BxUmjGOUNodHsLgAy+EgYJ/eT83ILSktQi/azUvOzMvGLd4pzEslRDAHpuIwfNAAAA[0mjenkins-slave1 in workspace /home/jenkins/workspace/Manoj_spark_build-ci
 > git rev-parse --is-inside-work-tree # timeout=10
Fetching changes from the remote Git repository
 > git config remote.origin.url git@github.com:Maruthi-Manoj/Spark.git # timeout=10
Fetching upstream changes from git@github.com:Maruthi-Manoj/Spark.git
 > git --version # timeout=10
using GIT_SSH to set credentials 
 > git fetch --tags --progress git@github.com:Maruthi-Manoj/Spark.git +refs/heads/*:refs/remotes/origin/*
 > git rev-parse refs/remotes/origin/Manoj-ci^{commit} # timeout=10
 > git rev-parse refs/remotes/origin/origin/Manoj-ci^{commit} # timeout=10
Checking out Revision 4d21be6619873014903d8be465b173507b123559 (refs/remotes/origin/Manoj-ci)
 > git config core.sparsecheckout # timeout=10
 > git checkout -f 4d21be6619873014903d8be465b173507b123559
Commit message: "example to find group by sum"
 > git rev-list --no-walk 4d21be6619873014903d8be465b173507b123559 # timeout=10
[Manoj_spark_build-ci] $ /bin/sh -xe /tmp/jenkins5108104733199540548.sh
+ find . -name '*.py'
+ xargs pyflakes
./example1/program/change.py:2: 'from pyspark.sql.types import *' used; unable to detect undefined names
./example1/program/change.py:2: 'pyspark.sql.types.*' imported but unused
./example1/program/change.py:4: 'datetime.date' imported but unused
./example1/program/join_two_csv_and_sum_using_dataframes.py:3: 'datetime.date' imported but unused
./example1/program/join_two_csv_and_sum_using_tempview.py:3: 'datetime.date' imported but unused
./example2/program/fakefriends_aggregate_using_dataframes.py:4: 'datetime.date' imported but unused
./example2/program/fakefriends_aggregate_using_tempview.py:3: 'datetime.date' imported but unused
./example2/program/fakefriends_aggregate_using_textFile.py:3: 'datetime.date' imported but unused
Build step 'Execute shell' marked build as failure
Build did not succeed and the project is configured to only push after a successful build, so no pushing will occur.
Finished: FAILURE
